[package]
name = "pomodorust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
term_size = "0.3.2"
colored = "2.0.0"
notifica = "3.0.2"
